import { Check, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { useProjectMilestones } from "@/hooks/useProjectMilestones";

export function ProjectMilestones({ projectId, canEdit }: { projectId: string; canEdit: boolean }) {
  const { milestones, loading, error, create, update, remove } = useProjectMilestones(projectId);
  const [title, setTitle] = useState("");
  const [actionError, setActionError] = useState<string | null>(null);
  async function add() { if (!title.trim()) return; try { await create(title.trim()); setTitle(""); setActionError(null); } catch (createError) { setActionError(createError instanceof Error ? createError.message : "Milestone could not be created."); } }
  async function toggle(id: string, completed: boolean) { try { await update(id, { status: completed ? "pending" : "completed", completed_at: completed ? null : new Date().toISOString() }); } catch (updateError) { setActionError(updateError instanceof Error ? updateError.message : "Milestone could not be updated."); } }
  const completed = milestones.filter((milestone) => milestone.status === "completed").length;
  return <section className="rounded-xl border border-border bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-xl font-bold">Milestones</h2><span className="text-sm text-muted">{completed} / {milestones.length}</span></div>{canEdit ? <div className="mt-5 flex gap-2"><input value={title} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void add(); }} placeholder="Add a milestone..." className="h-10 min-w-0 flex-1 rounded-md border border-border px-3 text-sm" /><Button size="sm" onClick={() => void add()}><Plus className="h-4 w-4" /> Add</Button></div> : null}{error || actionError ? <p className="mt-4 rounded-md bg-[#fad9db] px-3 py-2 text-sm" role="alert">{actionError ?? error}</p> : null}{loading ? <p className="mt-5 text-sm text-muted">Loading milestones...</p> : milestones.length ? <ul className="mt-5 space-y-2">{milestones.map((milestone) => <li key={milestone.id} className="flex items-center gap-3 rounded-md bg-surface px-3 py-3"><button type="button" disabled={!canEdit} onClick={() => void toggle(milestone.id, milestone.status === "completed")} aria-label={milestone.status === "completed" ? `Mark ${milestone.title} incomplete` : `Complete ${milestone.title}`} className={`grid h-6 w-6 shrink-0 place-items-center rounded border ${milestone.status === "completed" ? "border-foreground bg-foreground text-white" : "border-border"}`}>{milestone.status === "completed" ? <Check className="h-4 w-4" /> : null}</button><span className={`min-w-0 flex-1 text-sm ${milestone.status === "completed" ? "text-muted line-through" : "font-semibold"}`}>{milestone.title}</span>{canEdit ? <button type="button" onClick={() => void remove(milestone.id)} aria-label={`Delete ${milestone.title}`} className="text-muted hover:text-danger"><Trash2 className="h-4 w-4" /></button> : null}</li>)}</ul> : <EmptyState title="No milestones yet." description="Add a small sequence of outcomes to make progress visible." />}</section>;
}
