import { useState } from "react";
import { Check, Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { useProjectTodos } from "@/hooks/useProjectTodos";

export function ProjectTodoList({ projectId, canEdit }: { projectId: string; canEdit: boolean }) {
  const { todos, loading, error, create, update, remove } = useProjectTodos(projectId);
  const [title, setTitle] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const [actionError, setActionError] = useState<string | null>(null);
  async function addTodo() { if (!title.trim()) return; try { await create(title); setTitle(""); setActionError(null); } catch (todoError) { setActionError(todoError instanceof Error ? todoError.message : "Todo could not be added."); } }
  async function save(id: string) { if (!draft.trim()) return; try { await update(id, { title: draft.trim() }); setEditingId(null); setActionError(null); } catch (todoError) { setActionError(todoError instanceof Error ? todoError.message : "Todo could not be updated."); } }
  return <section className="rounded-xl border border-border bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-xl font-bold">Todo</h2><span className="text-sm text-muted">{todos.filter((todo) => !todo.completed).length} active</span></div>{canEdit ? <div className="mt-5 flex gap-2"><input value={title} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void addTodo(); }} placeholder="Add a task..." className="h-11 min-w-0 flex-1 rounded-md border border-border px-3" /><Button size="sm" onClick={() => void addTodo()}><Plus className="h-4 w-4" /> Add</Button></div> : null}{error || actionError ? <p className="mt-4 rounded-md bg-[#fad9db] px-4 py-3 text-sm" role="alert">{actionError ?? error}</p> : null}{loading ? <p className="mt-5 text-sm text-muted">Loading todos...</p> : todos.length ? <ul className="mt-5 space-y-2">{todos.map((todo) => <li key={todo.id} className="flex items-center gap-3 rounded-md bg-surface px-3 py-2">{canEdit ? <button type="button" aria-label={todo.completed ? "Mark incomplete" : "Mark complete"} className={`grid h-6 w-6 shrink-0 place-items-center rounded border ${todo.completed ? "border-foreground bg-foreground text-white" : "border-border"}`} onClick={() => void update(todo.id, { completed: !todo.completed })}>{todo.completed ? <Check className="h-4 w-4" /> : null}</button> : <span className="h-2 w-2 shrink-0 rounded-full bg-muted" />}{editingId === todo.id ? <input autoFocus value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void save(todo.id); if (event.key === "Escape") setEditingId(null); }} onBlur={() => void save(todo.id)} className="h-9 min-w-0 flex-1 rounded border border-border px-2 text-sm" /> : <span className={`min-w-0 flex-1 text-sm ${todo.completed ? "text-muted line-through" : ""}`}>{todo.title}</span>}{canEdit ? <div className="flex shrink-0 gap-1"><Button size="icon" variant="ghost" aria-label="Edit todo" onClick={() => { setEditingId(todo.id); setDraft(todo.title); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label="Delete todo" onClick={() => void remove(todo.id)}><Trash2 className="h-4 w-4" /></Button></div> : null}</li>)}</ul> : <div className="mt-5"><EmptyState title="No todos yet." description={canEdit ? "Add the next concrete step for this project." : "No tasks have been added to this project."} /></div>}</section>;
}