import { Bell, Check } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useRef, useState } from "react";
import { useNotifications } from "@/hooks/useWorkspaceFeatures";

export function NotificationBell() {
  const { notifications, unreadCount, markRead, markAllRead } = useNotifications();
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: PointerEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, []);
  return <div ref={ref} className="relative"><button type="button" onClick={() => setOpen((value) => !value)} aria-label={`Notifications${unreadCount ? `, ${unreadCount} unread` : ""}`} aria-expanded={open} className="relative grid h-10 w-10 place-items-center rounded-full text-muted hover:bg-surface hover:text-foreground"><Bell className="h-4 w-4" />{unreadCount ? <span className="absolute right-1 top-1 grid min-h-4 min-w-4 place-items-center rounded-full bg-foreground px-1 text-[10px] font-bold text-white">{unreadCount > 9 ? "9+" : unreadCount}</span> : null}</button>{open ? <div className="absolute right-0 top-full z-50 mt-2 w-[min(360px,calc(100vw-2rem))] overflow-hidden rounded-xl border border-border bg-white shadow-lift"><div className="flex items-center justify-between border-b border-border px-4 py-3"><p className="font-display font-bold">Notifications</p>{unreadCount ? <button type="button" onClick={() => void markAllRead()} className="text-xs font-semibold text-muted hover:text-foreground">Mark all read</button> : null}</div><div className="max-h-80 overflow-y-auto">{notifications.length ? notifications.map((item) => { const content = <div className={`border-b border-border px-4 py-3 text-left ${item.read_at ? "bg-white" : "bg-surface"}`}><div className="flex gap-2"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item.title}</p>{item.body ? <p className="mt-1 text-xs leading-5 text-muted">{item.body}</p> : null}<p className="mt-2 text-[11px] text-muted">{new Date(item.created_at).toLocaleString()}</p></div>{!item.read_at ? <Check className="h-4 w-4 shrink-0 text-muted" /> : null}</div></div>; return item.href ? <Link key={item.id} to={item.href} onClick={() => void markRead(item.id)}>{content}</Link> : <button key={item.id} type="button" className="block w-full" onClick={() => void markRead(item.id)}>{content}</button>; }) : <p className="px-4 py-8 text-center text-sm text-muted">You’re all caught up.</p>}</div></div> : null}</div>;
}
